name = "connecto-maintenance"
main = "worker.js"
compatibility_date = "2024-01-01"

# To deploy to connecto.fun zone, configure your zone_name / route:
# routes = [
#   { pattern = "connecto.fun/*", zone_name = "connecto.fun" }
# ]
