name = "connecto-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

workers_dev = true
preview_urls = true

routes = [
  { pattern = "connecto.fun/*", zone_name = "connecto.fun" },
  { pattern = "*.connecto.fun/*", zone_name = "connecto.fun" }
]


[[d1_databases]]
binding = "DB"
database_name = "connecto-db"
database_id = "c95366cb-6dde-4bfe-8a3e-f466969f1a16"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "REALTIME_ROOM", class_name = "ConnectoRealtimeRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ConnectoRealtimeRoom"]

